export const START_FETCHING_SUMMARY_RECORVERED =
  "features/SummaryRecorvered/START_FETCHING_SUMMARY_RECORVERED";
export const ERROR_FETCHING_SUMMARY_RECORVERED =
  "features/SummaryRecorvered/ERROR_FETCHING_SUMMARY_RECORVERED";
export const SUCCESS_FETCHING_SUMMARY_RECORVERED =
  "features/SummaryRecorvered/SUCCESS_FETCHING_SUMMARY_RECORVERED";

export const SET_OFFSET = "features/SummaryRecorvered/SET_OFFSET";
