export const START_FETCHING_SUMMARY_CONFIRMED =
  "features/SummaryConfirmed/START_FETCHING_SUMMARY_CONFIRMED";
export const ERROR_FETCHING_SUMMARY_CONFIRMED =
  "features/SummaryConfirmed/ERROR_FETCHING_SUMMARY_CONFIRMED";
export const SUCCESS_FETCHING_SUMMARY_CONFIRMED =
  "features/SummaryConfirmed/SUCCESS_FETCHING_SUMMARY_CONFIRMED";
