export const START_FETCHING_SUMMARY_DEATHS =
  "features/SummaryDeaths/START_FETCHING_SUMMARY_DEATHS";
export const ERROR_FETCHING_SUMMARY_DEATHS =
  "features/SummaryDeaths/ERROR_FETCHING_SUMMARY_DEATHS";
export const SUCCESS_FETCHING_SUMMARY_DEATHS =
  "features/SummaryDeaths/SUCCESS_FETCHING_SUMMARY_DEATHS";
